export const ADD_ITINERARIES = 'ADD_ITINERARIES';
export const ADD_ITINERARY = 'ADD_ITINERARY';
export const ITINERARY_ERROR = 'ITINERARY_ERROR';
export const SHOW_ITINERARY = 'SHOW_ITINERARY';
export const REMOVE_ITINERARY = 'REMOVE_ITINERARY';
